### ISSUE TITLE
LicenseFinder crashes with error "undefined method `sub' for [Array]"

### ISSUE THREAD

**Issue by camillem** [pivotal/LicenseFinder#435]
Hi,

Launching LicenseFinder on a Npm project causes it to crash with the error below. 
Anything I could do to investigate it more precisely ?
Thanks, 
Camille 

LicenseFinder version : license_finder-4.0.2
Installed with  sudo gem install license_finder
OS : Ubuntu 17.10 64 bits

```
$ license_finder
LicenseFinder::NPM: is active
/var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/license.rb:43:in `stripped_name': undefined method `sub' for ["Apache2", "MIT"]:Array (NoMethodError)
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/license.rb:20:in `block in find_by_name'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/license.rb:20:in `each'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/license.rb:20:in `detect'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/license.rb:20:in `find_by_name'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/package.rb:140:in `block in licenses_from_spec'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/package.rb:140:in `map'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/package.rb:140:in `licenses_from_spec'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/package.rb:131:in `licensing'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/package.rb:125:in `activations'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/package.rb:121:in `licenses'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/decision_applier.rb:47:in `with_approval'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/decision_applier.rb:30:in `block in apply_decisions'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/decision_applier.rb:30:in `map'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/decision_applier.rb:30:in `apply_decisions'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/decision_applier.rb:6:in `initialize'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/core.rb:72:in `new'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/core.rb:72:in `decision_applier'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/license_aggregator.rb:13:in `map'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/license_aggregator.rb:13:in `any_packages?'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/lib/license_finder/cli/main.rb:64:in `action_items'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /var/lib/gems/2.3.0/gems/license_finder-4.0.2/bin/license_finder:5:in `<top (required)>'
	from /usr/local/bin/license_finder:22:in `load'
	from /usr/local/bin/license_finder:22:in `<main>'
$ 
```

**Comment by xtreme-lisheng-tai** [comment]
This issue should be addressed by 
https://github.com/pivotal/LicenseFinder/pull/422/files

**Comment by camillem** [comment]
Great, thanks.

**Comment by seadowg** [comment]
@xtreme-lisheng-tai I'm seeing this as well (for an NPM project as well). Should it be fixed in 4.0.2 or is the fix still not released?

**Comment by xtreme-lisheng-tai** [comment]
@seadowg  Sorry, I should have been more clear. It has been fixed, but we have not released a version which contains the fix.

**Comment by seadowg** [comment]
@xtreme-lisheng-tai any plans to release soon? I'm blocked by this at the moment. I can pull down and build myself if not I guess.

**Comment by camillem** [comment]
@seadowg one possible workaround is to find the offending package.json and manually convert the array to a string. HTH
